### PR TITLE
Adds support for core Prawn's 'HTML-esque' color tag

### PR DESCRIPTION
**Pull request by allthesignals**
Addresses #15 by enabling support for Prawn core's `<color></color>` "HTML-esque" tag.

A few things I'm concerned about here:

1. I'm not sure I put these new methods (`#start_color` `#end_color`) in the _best_ place. Does it make sense to translate non-HTML this way? 
2. Not sure how best to test this either, but I'm looking at ways to improve this...

Thanks!

Here's some manual output to show this actually seems to work...

[test.pdf](https://github.com/puzzle/prawn-markup/files/8173224/test.pdf)

### CODE REVIEW

**Comment by codez** [comment]
Looks good to me. I do not know how to test colored text either. 

Prawns color tag also supports cmyk: "<color c='100' m='0' y='0' k='0'>and CMYK</color>" Do you think you could integrate this too?

I adjusted the build.yml hoping to get the checks working for the pull requests, too.

**Comment by allthesignals** [comment]
> Looks good to me. I do not know how to test colored text either.
> 
> Prawns color tag also supports cmyk: "and CMYK" Do you think you could integrate this? Adding the color tag to the text semantics list in the Readme would be great, too.
> 
> I adjusted the build.yml hoping to get the checks working for the pull requests, too.

Thanks for the feedback. Yeah! I just pushed up a change. Not sure it's the most "rubyist" way. Let me know if there's a more preferred way to deal with hash destructuring :)

**Comment by codez** [comment]
Great, thank you for your contribution!

**Comment by codez** [comment]
I managed to get the checks running. Once rubocop is happy, I will merge your request.

**Comment by allthesignals** [comment]
Thanks, @codez! Fixed the linting issues. I saw code coverage check failed but seemed to be a configuration issue.

**Comment by allthesignals** [comment]
Hi @codez any other feedback?

**Comment by codez** [comment]
Thank you for the contribution!

**Pull request merged**
